name: configuration-mode
components:
- id: main
  label: Configuration
  capabilities:
  - id: platinummassive43262.firmwareVersion
    version: 1
  - id: platinummassive43262.pe653PoolSpaConfig
    version: 1
  - id: platinummassive43262.pe653PumpTypeConfig
    version: 1
  - id: platinummassive43262.pe653BoosterPumpConfig
    version: 1
  - id: refresh
    version: 1
  categories:
    - name: WaterValve
- id: heater
  label: Heater Configuration
  capabilities:
  - id: platinummassive43262.pe653FiremanConfig
    version: 1
  - id: platinummassive43262.pe653HeaterSafetyConfig
    version: 1
  categories:
    - name: WaterValve
- id: vsp
  label: Variable Speed Pump Configuration
  capabilities:
  - id: platinummassive43262.pe653VspSpeed1Config
    version: 1
  - id: platinummassive43262.pe653VspSpeed2Config
    version: 1
  - id: platinummassive43262.pe653VspSpeed3Config
    version: 1
  - id: platinummassive43262.pe653VspSpeed4Config
    version: 1
  - id: platinummassive43262.pe653VspMaxSpeedConfig
    version: 1
  categories:
    - name: WaterValve
- id: freezeControl
  label: Freeze Control Configuration
  capabilities:
  - id: platinummassive43262.pe653FreezeTemperature
    version: 1
  - id: platinummassive43262.pe653Circuit1Freeze
    version: 1
  - id: platinummassive43262.pe653Circuit2Freeze
    version: 1
  - id: platinummassive43262.pe653Circuit3Freeze
    version: 1
  - id: platinummassive43262.pe653Circuit4Freeze
    version: 1
  - id: platinummassive43262.pe653Circuit5Freeze
    version: 1
  - id: platinummassive43262.pe653VspFreeze
    version: 1
  - id: platinummassive43262.pe653PoolSpaFreezeCycle
    version: 1
  - id: platinummassive43262.pe653HeaterFreeze
    version: 1
  categories:
    - name: WaterValve
- id: temperatureOffsets
  label: Temperature Offsets
  capabilities:
  - id: platinummassive43262.pe653WaterOffset
    version: 1
  - id: platinummassive43262.pe653AirOffset
    version: 1
  - id: platinummassive43262.pe653SolarOffset
    version: 1
  categories:
    - name: WaterValve
metadata:
  deviceType: WaterValve
  ocfDeviceType: oic.d.watervalve
  deviceTypeId: WaterValve
preferences:
  - title: "Mode"
    name: mode
    description: "Switch between configuration and operation mode"
    required: true
    preferenceType: enumeration
    definition:
      options:
        configuration: "Configuration Mode"
        operation: "Operation Mode"
      default: configuration
  - title: "Change Profile"
    name: changeProfile
    description: "Choose profile to use"
    required: true
    preferenceType: enumeration
    definition:
      options:
        p_ssss__hwa_: "P_-SSSS_-_-H-WA_"
        p_ssss__hwas: "P_-SSSS_-_-H-WAS"
        p_sssss__wa_: "P_-SSSSS-_-_-WA_"
        p_sssss__was: "P_-SSSSS-_-_-WAS"
        pssss___hwas: "PS-SSS__-_-H-WAS"
        pssss__vhwas: "PS-SSS__-V-H-WAS"
        pssss_sv_was: "PS-SSS_S-V-_-WAS"
        pssssssvhwas: "PS-SSSSS-V-H-WAS"
      default: pssssssvhwas
  - title: "Time Zone (offset from UTC)"
    name: timezoneUTC
    description: "Enter the local time zone offset from UTC (-12 to +14 hours)"
    required: true
    preferenceType: integer
    definition:
      minimum: -12
      maximum: 14
      default: -5
  - title: "Daylight Savings Time"
    name: timezoneDST
    description: "Change the PE653 time to reflect daylight savings vs standard time."
    required: true
    preferenceType: enumeration
    definition:
      options:
        0: "Standard time (winter)"
        1: "Daylight savings time (summer)"
      default: 0
  - title: "Water Temperature Offset"
    name: offsetWater
    description: "Water temperature offset (-5 to +5 degrees F)"
    required: true
    preferenceType: integer
    definition:
      minimum: -5
      maximum: 5
      default: 0
  - title: "Air Temperature Offset"
    name: offsetAir
    description: "Air temperature offset (-5 to +5 degrees F)"
    required: true
    preferenceType: integer
    definition:
      minimum: -5
      maximum: 5
      default: 0
  - title: "Solar Temperature Offset"
    name: offsetSolar
    description: "Solar temperature offset (-5 to +5 degrees F)"
    required: true
    preferenceType: integer
    definition:
      minimum: -5
      maximum: 5
      default: 0
  - title: "Thermostat Setpoint Scale"
    name: setpointScale
    description: "Some firmware versions require the alternate setpoint scale. If thermostat setpoint changes do not work, try changing this setting."
    required: true
    preferenceType: enumeration
    definition:
      options:
        0: "0 - default"
        1: "1 - alternate"
      default: 0
  - title: "Z-Wave Delay (in milliseconds)"
    name: zwDelay
    description: "Delay between z-wave commands sent to the PE653. Default is 1000ms (1s)."
    required: true
    preferenceType: integer
    definition:
      minimum: 0
      maximum: 10000
      default: 1000